name: linebo-zombihop
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - matplotlib
  - scikit-optimize
  - spyder-kernels=2.5
  - joblib
prefix: /u/08/atiihone/unix/anaconda3/envs/linebo-zombihop
