name: linebo-zombihop
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alabaster=0.7.12=py37_0
  - arrow=1.2.3=py37h06a4308_1
  - astroid=2.14.2=py37h06a4308_0
  - atomicwrites=1.4.0=py_0
  - attrs=22.1.0=py37h06a4308_0
  - autopep8=1.6.0=pyhd3eb1b0_1
  - babel=2.11.0=py37h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=22.6.0=py37h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - ca-certificates=2023.7.22=hbcca054_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py37h5eee18b_3
  - chardet=4.0.0=py37h06a4308_1003
  - click=8.0.4=py37h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.6=py37h06a4308_0
  - cookiecutter=1.7.3=pyhd3eb1b0_0
  - cryptography=39.0.1=py37h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py37h295c915_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - dill=0.3.6=py37h06a4308_0
  - docutils=0.17.1=py37h06a4308_1
  - entrypoints=0.4=py37h06a4308_0
  - expat=2.5.0=h6a678d5_0
  - fftw=3.3.9=h27cfd23_1
  - flake8=4.0.1=pyhd3eb1b0_1
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.12.1=h4a9f257_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py37h06a4308_0
  - imagesize=1.4.1=py37h06a4308_0
  - importlib-metadata=3.10.0=py37h06a4308_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - inflection=0.5.1=py37h06a4308_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.1=py37h06a4308_1
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jellyfish=0.9.0=py37h7f8727e_0
  - jinja2=3.1.2=py37h06a4308_0
  - jinja2-time=0.2.0=pyhd3eb1b0_3
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9e=h5eee18b_1
  - jsonschema=4.17.3=py37h06a4308_0
  - jupyter_client=7.4.9=py37h06a4308_0
  - jupyter_core=4.11.2=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.4.0=py37h06a4308_0
  - krb5=1.20.1=h568e23c_1
  - lazy-object-proxy=1.6.0=py37h27cfd23_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=ha637b67_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libevent=2.1.12=h8f2d780_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libllvm14=14.0.6=hdb19cb5_3
  - libpng=1.6.39=h5eee18b_0
  - libpq=12.15=h37d81fd_1
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.5.1=h6a678d5_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libxslt=1.1.37=h2085143_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-base=2.2.4=py37hfd891ef_0
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - mypy_extensions=0.4.3=py37h06a4308_1
  - mysql=5.7.24=he378463_2
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.4.1=py37h06a4308_0
  - nbformat=5.7.0=py37h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py37h06a4308_0
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy-base=1.21.5=py37ha15fc14_3
  - numpydoc=1.5.0=py37h06a4308_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=22.0=py37h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.10.3=py37h06a4308_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=22.3.1=py37h06a4308_0
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - platformdirs=2.5.2=py37h06a4308_0
  - pluggy=1.0.0=py37h06a4308_1
  - ply=3.11=py37_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.36=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pyaml=17.12.1=py_0
  - pycodestyle=2.8.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.3.0=py37h06a4308_0
  - pyflakes=2.4.0=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.16.2=py37h06a4308_0
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py37h06a4308_0
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyqt=5.15.7=py37h6a678d5_1
  - pyqt5-sip=12.11.0=py37h6a678d5_1
  - pyqtwebengine=5.15.7=py37h6a678d5_1
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - python-lsp-black=1.2.1=py37h06a4308_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.5.0=py37h06a4308_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - pytoolconfig=1.2.5=py37h06a4308_1
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py37h5eee18b_1
  - pyzmq=23.2.0=py37h6a678d5_0
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.2.2=py37h06a4308_0
  - qt-main=5.15.2=h5b8104b_9
  - qt-webengine=5.15.9=h9ab4d14_7
  - qtawesome=1.2.2=py37h06a4308_0
  - qtconsole=5.3.2=py37h06a4308_0
  - qtpy=2.2.0=py37h06a4308_0
  - qtwebkit=5.212=h3fafdc1_5
  - readline=8.2=h5eee18b_0
  - rope=1.7.0=py37h06a4308_0
  - rtree=1.0.1=py37h06a4308_0
  - scikit-learn=1.0.2=py37h51133e4_1
  - scikit-optimize=0.9.0=pyhd8ed1ab_1
  - secretstorage=3.3.1=py37h06a4308_0
  - setuptools=65.6.3=py37h06a4308_0
  - sip=6.6.2=py37h6a678d5_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.3.3=py37h06a4308_0
  - spyder-kernels=2.3.3=py37h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - testpath=0.6.0=py37h06a4308_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss2=1.2.1=py37h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tomli=2.0.1=py37h06a4308_0
  - tomlkit=0.11.1=py37h06a4308_0
  - tornado=6.2=py37h5eee18b_0
  - traitlets=5.7.1=py37h06a4308_0
  - typed-ast=1.4.3=py37h7f8727e_1
  - typing_extensions=4.4.0=py37h06a4308_0
  - ujson=5.4.0=py37h6a678d5_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - watchdog=2.1.6=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - whatthepatch=1.0.2=py37h06a4308_0
  - wheel=0.38.4=py37h06a4308_0
  - wrapt=1.14.1=py37h5eee18b_0
  - wurlitzer=3.0.2=py37h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - charset-normalizer==3.3.0
      - codecov==2.1.13
      - coverage==7.2.7
      - cython==3.0.3
      - decorator==5.1.0
      - diversipy==0.8
      - emcee==2.2.1
      - gpy==1.10.0
      - kiwisolver==1.4.5
      - matplotlib==3.1.3
      - mock==4.0.3
      - n-sphere==1.2.0
      - nose==1.3.7
      - numpy==1.21.3
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - pandas==1.3.4
      - pydoe==0.3.8
      - python-ternary==1.0.8
      - pytz==2023.3.post1
      - requests==2.31.0
      - scipy==1.4.1
      - seaborn==0.11.2
      - six==1.16.0
      - sobol-seq==0.2.0
      - torch==1.13.1
      - typing-extensions==4.7.1
      - urllib3==2.0.6
prefix: /u/08/atiihone/unix/anaconda3/envs/linebo-zombihop
